version: '3.8'

volumes:
  mongodb_data:

services:
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./FormChecker/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - mongodb
    command: >
      sh -c "sleep 10 && python manage.py runserver 0:8000"
