version: "3.9"

services:
  mongodb:
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    hostname: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data-mongodb:/data/db

  backend:
    build:
      context: ./FormChecker/
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
