# Generated by Django 4.1.13 on 2024-12-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtemplate',
            options={'ordering': ('name',), 'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название формы'),
        ),
    ]
